groups:
  - name: fastapi-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[1m]) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate ({{ $value }} rps)"
          description: "Request rate is above 2 requests/sec for more than 1 minute."

      - alert: High5xxRate
        expr: (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
          description: "5xx errors are more than 5% of total requests over the last 5 minutes."
