groups:
  - name: fastapi-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[1m]) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate ({{ $value }} rps)"
          description: "Request rate is above 2 requests/sec for more than 1 minute."

      - alert: High5xxRate
        expr: (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
          description: "5xx errors are more than 5% of total requests over the last 5 minutes."

      - alert: BackendDown
        expr: up{job="fastapi"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend is down"
          description: "Prometheus cannot scrape backend metrics for 1 minute."

      - alert: SlowResponseTime
        expr: rate(http_request_duration_highr_seconds_sum[5m]) / rate(http_request_duration_highr_seconds_count[5m]) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time ({{ $value }}s)"
          description: "Average response time is above 1 second for more than 2 minutes."
